toc:
  - title: Pre-planned kits
    slug: offerings
    url: offerings
  - title: Custom DIY
    slug: offerings
    url: offerings
  - title: Journal
    slug: journal
    url: journal
  - title: About
    slug: about
    url: about

    

