toc:
  - title: Pre-planned kits
    slug: preplanned
    url: preplanned
  - title: Custom DIY
    slug: custom
    url: custom
  - title: Journal
    slug: journal
    url: journal
  - title: About
    slug: about
    url: about

    

